const nameList = [
    'newuser11',
    'newuser42',
    'Laggingnag',
    'Sensibilia',
    'Sporogenesis',
    'TheRooster',
    'Spectator00',
    'superuserdont',
    'passablequit',
    'VerbNoun',
    'jumpShot88',
    'mad max',
    'Admin',
    'Super Admin',
    'Garry',
    'KarenBot9000',
    'SmiteOnGaren',
    'var_charazard',
    'Dw',
    'camel_case',
    'Attorney @ Law',
    'windowsnine',
    'mac',
    'new_user',
    'some-username7',
    'Rich Guy',
    'cowboy',
    'CouboSelcouth',
    'JuliusSeizure',
    'BackStabbath',
    'MasterOfnone',
    'tyler',
    'noname',
    'new.person'  
]

export default nameList